CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C     INTEGER FUNCTION LENC (CHARACTER*(*) C)
C     
C     INTEGER FUNCTION LENC WILL RETURN THE INTEGER LENGTH OF CHARACTER STRING C
C     
C     INPUT FACTORS:
C     
C     C     
C           THE CHARACTER STRING WHOSE LENGTH IS NEEDED
C     
C     OUTPUT:
C     
C     LENC(C)
C           THE INTEGER LENGTH OF CHARACTER STRING C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC      
      INTEGER FUNCTION LENC(C)
      IMPLICIT NONE
      CHARACTER*(*) C
      INTEGER I
      I=1
  12  IF(C(I:I) .NE. ' ') THEN
      I=I+1
      GOTO 12 
      ENDIF
      LENC=I-1
      RETURN 
      END

